plugins {
	id 'java-library'
	id 'maven-publish'
	id 'io.freefair.lombok' version '9.5.0'
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
	modularity.inferModulePath = true
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

group = 'org.desertskyrangers'
version = '0.1-SNAPSHOT'
description = 'Caspian CFD Solver'

sourceSets {
	main.java.srcDirs = ['source/main/java']
	main.resources.srcDirs = ['source/main/resources']
	test.java.srcDirs = ['source/test/java', 'source/testIt/java']
	test.resources.srcDirs = ['source/test/resources', 'source/testIt/resources']
}

repositories {
	mavenCentral()
}

ext.configDir = 'gradle/config'
apply from: "$rootDir/$configDir/test.gradle"
