name: CI

on: [ push ]

env:
  JAVA_VERSION: "17"
  DSR_GPG_PASSWORD: ${{ secrets.DSR_GPG_PASSWORD }}
  DSR_REPO_USERNAME: ${{ secrets.DSR_REPO_USERNAME }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]
    steps:
      - name: Fetch sources
        uses: actions/checkout@v2

      - name: Fetch CI/CD resources
        uses: actions/checkout@v2
        with:
          repository: desertskyrangers/cicd
          path: .github

      - name: Configuration
        shell: bash
        run: |
          source .github/config.sh

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{env.JAVA_VERSION}}

      - name: Maven Repository Cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}

      - name: Build Code
        run: |
           ./gradlew clean check

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
